### ISSUE TITLE
Can i use Flatlist instead of ScrollView?

### ISSUE THREAD

**Issue by MoeMamdouh** [rgommezz/reanimated-collapsible-navbar#4]
Hello, thank you for this great implementation, i have a question
Can i use Flatlist instead of ScrollView?, Does the reanimated library support the Flatlist?

**Comment by rgommezz** [comment]
Hi @MoeMamdouh,

Absolutely, `Flatlist` extends the ScrollView, so it's supported. The same applies for the `SectionList`
